# Research Sources

youtube:
  - name: Rob Walling
    url: https://www.youtube.com/@RobWalling/videos

  - name: Simon Høiberg
    url: https://www.youtube.com/@SimonHoiberg/videos

  - name: Marc Lou
    url: https://www.youtube.com/@marc-lou/videos

  - name: Nathan Latka
    url: https://www.youtube.com/@NathanLatkawatch/videos

  - name: Dan Martell
    url: https://www.youtube.com/@danmartell/videos

  - name: TK Kader
    url: https://www.youtube.com/@TKKader/videos
  
  - name: Braden Ricchini
    url: https://www.youtube.com/@bradenricchini/videos

  - name: Jonathan Rintala
    url: https://www.youtube.com/@JonathanRintala/videos

  - name: Sam Dunning
    url: https://www.youtube.com/@SamDunning/videos

  - name: Justin Kan
    url: https://www.youtube.com/@JustinKanTV/videos

  - name: Samu Kovács
    url: https://www.youtube.com/@SamuKovacs/videos

linkedin:
  - name: Rob Walling
    url: https://www.linkedin.com/in/robwalling/recent-activity/all/

  - name: Simon Høiberg
    url: https://www.linkedin.com/in/simonhoiberg/recent-activity/all/

  - name: Marc Lou
    url: https://www.linkedin.com/in/marclouvion/recent-activity/all/

  - name: Nathan Latka
    url: https://www.linkedin.com/in/nathanlatka/recent-activity/all/

  - name: Dan Martell
    url: https://www.linkedin.com/in/dmartell/recent-activity/all/

  - name: TK Kader
    url: https://www.linkedin.com/in/tkkader/recent-activity/all/

  - name: Braden Ricchini
    url: https://www.linkedin.com/in/braden-ricchini-1b5b64324/recent-activity/all/

  - name: Jonathan Rintala
    url: https://www.linkedin.com/in/jonathan-rintala/recent-activity/all/

  - name: Sam Dunning
    url: https://www.linkedin.com/in/samdunning/recent-activity/all/

  - name: Justin Kan
    url: https://www.linkedin.com/in/justinkan/recent-activity/all/

  - name: Samu Kovács
    url: https://www.linkedin.com/in/samu-kovacs/recent-activity/all/
